### ISSUE TITLE
Przebicie

### ISSUE THREAD

**Issue by geodotka** [mysthea/rcon#2]
Formularz do obliczania przebicia

**Comment by geodotka** [comment]
Stworzyć:
- [x] niezbędne modele,
- [x] formularz,
- [x] templatkę,
- [x] widok do obliczania wyników

**Comment by mysthea** [comment]
Comboboxy (nazwy) do osobnego zapisania w bazie razem z ich "zawartością" (po polsku do wyświetlania):
Beton = c_class -> 'C12/15', 'C16/20', 'C20/25', 'C25/30', 'C30/37', 'C35/45', 'C40/50', 'C45/55', 'C50/60', 'C55/67', 'C60/75', 'C70/85', 'C80/95', 'C90/105'
Stal = s_class -> 'RB400', 'RB400W', '35G2Y', '34GS', 'BSt420', '20G2VY-b', 'RB500', 'RB500W', 'B500SP', 'BSt500'
fi.sw (średnica) = dsw -> 6 mm, 8 mm, 10 mm, 12 mm, 16 mm
Podpora = support -> słup wewnętrzny, słup krawędziowy, słup narożny, ściana - naroże, ściana - koniec
Przekrój = sect -> prostokątny, kołowy
Sytuacja obliczeniowa = dsit -> trwała, przejściowa, wyjątkowa

Pola typu 'Edit':
b = b itd.
lambda_u
asx
asy
ved
beta
vrdc - w tym polu będą wyświetlane dane po obliczeniu, a nie sczytywane
vrdmax - j.w.: w tym polu będą wyświetlane dane po obliczeniu, a nie sczytywane
